CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
full_name varchar(50),
email varchar(80) UNIQUE NOT NULL,
password varchar(80) NOT NULL,
reg_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE groups (
id INT AUTO_INCREMENT PRIMARY KEY,
name varchar(50) NOT NULL
)

CREATE TABLE bills (
id INT AUTO_INCREMENT PRIMARY KEY,
group_id INT NOT NULL,
amount DECIMAL(5,2) NOT NULL,
description VARCHAR(100),
FOREIGN KEY (group_id) REFERENCES groups(id)
)

CREATE TABLE accounts (
id INT AUTO_INCREMENT PRIMARY KEY,
group_id INT NOT NULL,
user_id INT NOT NULL,
FOREIGN KEY (group_id) REFERENCES groups(id),
FOREIGN KEY (user_id) REFERENCES users(id)
)